### ISSUE TITLE
Issue with python encoder and msp2db library

### ISSUE THREAD

**Issue by hannierpulido** [computational-metabolomics/msp2db#9]
Hello, 
I am testing the msp2db package in Spyder-Python 3.8 and run into this error when trying to convert a .msp library
```r
create_db(file_pth=db_pth)
libdata = LibraryData(msp_pth="C:/Users/hannierp/Downloads/MoNA-export-LC-MS-MS_Negative_Mode.msp", db_pth = db_pth, schema = "mona")
```
```r
Traceback (most recent call last):

  File "C:\Users\hannierp\AppData\Local\Temp/ipykernel_11124/3969560687.py", line 1, in <module>
    libdata = LibraryData(msp_pth="C:/Users/hannierp/Downloads/MoNA-export-LC-MS-MS_Negative_Mode.msp", db_pth = db_pth, schema = "mona")

  File "C:\Users\hannierp\Anaconda3\lib\site-packages\msp2db\parse.py", line 115, in __init__
    self._parse_files(msp_pth, chunk, db_type, celery_obj=celery_obj,

  File "C:\Users\hannierp\Anaconda3\lib\site-packages\msp2db\parse.py", line 199, in _parse_files
    self.num_lines = line_count(msp_pth)

  File "C:\Users\hannierp\Anaconda3\lib\site-packages\msp2db\utils.py", line 42, in line_count
    for i, l in enumerate(f):

  File "C:\Users\hannierp\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]

UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 6631: character maps to <undefined>
```

Any leads about this error, it seems a conflict with the python encoder.

Thanks,

**Comment by Tomnl** [comment]
Hi @hannierpulido, could you provide the file ( or a subset of the file) you are using please

**Comment by hannierpulido** [comment]
Hi @Tomnl 
I got the .msp library from [here](https://mona.fiehnlab.ucdavis.edu/rest/downloads/retrieve/05e74eda-6d98-11e7-907b-a6006ad3dba0)

Thanks,

**Comment by Tomnl** [comment]
Hi @hannierpulido, 

just running on my Linux (ubuntu) machine and not getting any problems. It could be a problem between Unix/Linux and Windows. 

Can you run the following command in your Spyder-python 3.8 setup

```
import sys
sys.getdefaultencoding()
```

Can I also check how you installed the package?
